### ISSUE TITLE
Getting errors from Lyric setup

### ISSUE THREAD

**Issue by CyberDefenseTiger** [jasondefuria/Honeywell-Lyric#5]
Thank you for this i tried several different projects and yours is the first one i could get to work.

I have not messed around to see if controlling it actually works but it is getting sensor data from my t5.  Though my logs give a bunch of errors.  I dont know if this is just me or is wide spread.  I have not really done anything to since i set it up on Saturday 9/26

2020-09-29 10:23:52 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for lyric-new doing I/O at custom_components/lyric-new/__init__.py, line 92: if not lyric.locations:
2020-09-29 10:23:52 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for lyric-new doing I/O at custom_components/lyric-new/__init__.py, line 92: if not lyric.locations:
2020-09-29 10:23:52 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing lyric/media_source.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 30, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 401, in get_platform
    cache[full_name] = importlib.import_module(
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.lyric-new.media_source'
2020-09-29 10:23:52 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing lyric/logbook.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 30, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 401, in get_platform
    cache[full_name] = importlib.import_module(
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.lyric-new.logbook'
2020-09-29 10:23:52 WARNING (MainThread) [homeassistant.components.climate] ClimateDevice is deprecated, modify LyricThermostat to extend ClimateEntity

**Comment by jasondefuria** [comment]
Yeah...This is because of recent rewrites. https://github.com/home-assistant/core/pull/39695 is the most up-to-date pull/rewrite.
